### ISSUE TITLE
Can you update it because it's outdated?

### ISSUE THREAD

**Issue by Cristofer543** [zvbt/Viki-Volume-Control#1]
Update the extension because it's no longer working. Look, I created one there and it works well, update yours now."

**Comment by zvbt** [comment]
What browser are you using ?

**Comment by Cristofer543** [comment]
@zvbt I use Chrome, When I tried to use your extension it didn't work, I created a mini extension but for viki.com.

**Comment by zvbt** [comment]
make sure that your other extension don't interfere with the mouse wheel key binds

**Comment by Cristofer543** [comment]
Nothing to interfere with that, when I put it on it didn't work.

**Comment by zvbt** [comment]
I tried it on a fresh install of Google Chrome and it works correctly.
The extension doesn't have a GUI or anything it only uses the mouse wheel to decrease or increase the volume.
If you encounter the error message "Unrecognized manifest key browser_specific_settings" the extension should still function

**Comment by Cristofer543** [comment]
I understand and a doubt why don't you make a Gui to make it look better and to have intrutions ?

**Comment by zvbt** [comment]
At first it was just a personal project i didn't know that people would use it.
I will create a gui soon when i have the time.

**Comment by Cristofer543** [comment]
Yes people must like it because viki.com doesn't have that feature built in, I tried to put it in the viki options menu but I couldn't :V
